# report_generator.py
# Report export utilities for H-SAFE Firewall Simulator

import json
import csv
import textwrap
import os
from datetime import datetime
from typing import Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import cm

# =========================
# JSON EXPORT
# =========================

def export_json(report: Dict, output_path: str) -> None:
    """
    Export analysis report as JSON.
    """
    final_report = report.copy()
    final_report["exported_at"] = datetime.now().isoformat()
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(final_report, f, indent=4)


# =========================
# CSV EXPORT
# =========================

def export_csv(report: Dict, output_path: str) -> None:
    """
    Export key report sections as CSV.
    """
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        
        # Metadata
        writer.writerow(["METADATA", "Exported At", datetime.now().isoformat()])
        writer.writerow([])

        # Overview
        writer.writerow(["SECTION", "KEY", "VALUE"])
        for key, value in report["overview"].items():
            writer.writerow(["OVERVIEW", key, value])

        # Traffic profile
        for proto, count in report["traffic_profile"]["by_protocol"].items():
            writer.writerow(["PROTOCOL", proto, count])

        for lane, count in report["traffic_profile"]["by_lane"].items():
            writer.writerow(["LANE", lane, count])

        # Rule hits
        for rule_id, hits in report["security_findings"]["rule_hit_count"].items():
            writer.writerow(["RULE_HITS", rule_id, hits])

        # Severity distribution
        for sev, count in report["security_findings"]["severity_distribution"].items():
            writer.writerow(["SEVERITY", sev, count])

        # Top targets
        for asset in report["security_findings"]["top_targeted_assets"]:
            writer.writerow(
                ["TOP_TARGET", asset["ip"], asset["hits"]]
            )


# =========================
# PDF EXPORT (Advanced Layout)
# =========================

COLOR_BG = colors.HexColor("#0f172a")     # Slate 900
COLOR_PANEL = colors.HexColor("#1e293b")  # Slate 800
COLOR_TEXT_MAIN = colors.white
COLOR_TEXT_SUB = colors.HexColor("#94a3b8") # Slate 400
COLOR_ACCENT_BLUE = colors.HexColor("#3b82f6")
COLOR_ACCENT_RED = colors.HexColor("#ef4444")
COLOR_ACCENT_YELLOW = colors.HexColor("#eab308")
COLOR_ACCENT_GREEN = colors.HexColor("#22c55e")

def export_pdf(report: Dict, output_path: str, timeline: List[Dict] = []) -> None:
    """
    Export analysis report as a high-fidelity PDF with Dark Theme.
    timeline: Full list of packets for detailed table.
    """
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    
    meta = report.get("meta", {})
    filename_display = meta.get("filename", "simulation.pcap")
    timestamp_display = meta.get("timestamp", datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"))
    report_id = meta.get("report_id", "N/A")
    
    current_y = height

    def draw_background():
        c.setFillColor(COLOR_BG)
        c.rect(0, 0, width, height, fill=1, stroke=0)
    
    def draw_footer(page_num):
        c.setFillColor(COLOR_TEXT_SUB)
        c.setFont("Helvetica", 8)
        c.drawString(40, 30, "Generated by H-SAFE Security Engine")
        c.drawRightString(width - 40, 30, f"Page {page_num}")

    def new_page():
        nonlocal current_y
        c.showPage()
        draw_background()
        draw_footer(c.getPageNumber())
        current_y = height - 50

    # --- PAGE 1 ---
    draw_background()
    draw_footer(1)
    
    # 1. HEADER
    current_y -= 60
    c.setFillColor(COLOR_ACCENT_BLUE)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(40, current_y + 35, "CYBERSECURITY ANALYSIS")
    
    c.setFillColor(COLOR_TEXT_MAIN)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(40, current_y, "H-SAFE Firewall Traffic Report")
    
    current_y -= 30
    c.setStrokeColor(COLOR_PANEL)
    c.setLineWidth(1)
    c.line(40, current_y, width - 40, current_y)
    
    current_y -= 25
    c.setFont("Helvetica", 10)
    c.setFillColor(COLOR_TEXT_SUB)
    c.drawString(40, current_y, "File Name:")
    c.setFillColor(COLOR_TEXT_MAIN)
    c.drawString(100, current_y, filename_display)
    
    c.setFillColor(COLOR_TEXT_SUB)
    c.drawString(300, current_y, "Timestamp:")
    c.setFillColor(COLOR_TEXT_MAIN)
    c.drawString(360, current_y, timestamp_display)
    
    current_y -= 15
    c.setFillColor(COLOR_TEXT_SUB)
    c.drawString(40, current_y, "Report ID:")
    c.setFillColor(COLOR_TEXT_MAIN)
    c.drawString(100, current_y, report_id)

    # 2. KPI CARDS
    current_y -= 50
    card_width = (width - 80 - 30) / 4 # 4 cards, 30px total gap
    card_height = 70
    
    def draw_card(x, title, value, color):
        # Card BG
        c.setFillColor(COLOR_PANEL)
        c.roundRect(x, current_y - card_height, card_width, card_height, 8, fill=1, stroke=0)
        # Border Accent
        c.setFillColor(color)
        c.rect(x, current_y - card_height, 4, card_height, fill=1, stroke=0) # Left stripe
        # Title
        c.setFillColor(COLOR_TEXT_SUB)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(x + 15, current_y - 20, title.upper())
        # Value
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 18)
        c.drawString(x + 15, current_y - 50, str(value))
    
    vals = report.get("overview", {})
    draw_card(40, "Processed Pkts", vals.get("total_packets", 0), COLOR_TEXT_MAIN)
    draw_card(40 + card_width + 10, "Threats Blocked", vals.get("blocked_packets", 0), COLOR_ACCENT_RED)
    draw_card(40 + (card_width + 10)*2, "Alerts Triggered", vals.get("total_alerts", 0), COLOR_ACCENT_YELLOW)
    draw_card(40 + (card_width + 10)*3, "Max Severity", vals.get("highest_severity", "N/A"), COLOR_ACCENT_BLUE)
    
    current_y -= (card_height + 40)

    # 3. ENGINE ASSESSMENT
    c.setFillColor(COLOR_TEXT_MAIN)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, current_y, "Engine Assessment")
    
    # Add Duration info here
    c.setFillColor(COLOR_TEXT_SUB)
    c.setFont("Helvetica", 10)
    duration = vals.get("duration_seconds", 0)
    c.drawRightString(width - 40, current_y, f"Scan Duration: {duration}s")
    
    current_y -= 15
    
    # Text Panel
    text = report.get("assessment", "No assessment available.")
    text_obj = c.beginText(55, current_y - 15)
    text_obj.setFont("Helvetica", 10)
    text_obj.setFillColor(COLOR_TEXT_MAIN)
    lines = textwrap.wrap(text, width=95)
    
    panel_height = len(lines) * 14 + 30
    c.setFillColor(COLOR_PANEL)
    c.roundRect(40, current_y - panel_height, width - 80, panel_height, 8, fill=1, stroke=0)
    
    # Highlight bar based on severity
    sev = vals.get("highest_severity", "LOW")
    bar_color = COLOR_ACCENT_RED if sev == "HIGH" else (COLOR_ACCENT_YELLOW if sev == "MEDIUM" else COLOR_ACCENT_GREEN)
    c.setFillColor(bar_color)
    c.rect(40, current_y - panel_height, 4, panel_height, fill=1, stroke=0)

    for line in lines:
        text_obj.textLine(line)
    c.drawText(text_obj)
    
    current_y -= (panel_height + 40)

    # 4. NETWORK FLOW VISUALIZATION
    c.setFillColor(COLOR_TEXT_MAIN)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, current_y, "Live Packet Flow Visualization")
    current_y -= 10
    
    # Draw Schematic
    viz_y = current_y - 80
    
    # Source
    c.setFillColor(COLOR_ACCENT_BLUE)
    c.circle(100, viz_y, 20, fill=1, stroke=0)
    
    # Dest
    c.setFillColor(COLOR_ACCENT_GREEN)
    c.circle(width - 100, viz_y, 20, fill=1, stroke=0)
    
    # Line
    c.setStrokeColor(colors.gray)
    c.setLineWidth(2)
    c.line(100, viz_y, width - 100, viz_y)
    
    # Firewall Icon (Logo)
    current_dir = os.path.dirname(os.path.abspath(__file__))
    logo_path = os.path.join(current_dir, "..", "public", "assets", "H-Safe-Logo.png")
    
    if os.path.exists(logo_path):
        c.drawImage(logo_path, width/2 - 25, viz_y - 25, width=50, height=50, mask='auto', preserveAspectRatio=True)
    else:
        c.setFillColor(colors.HexColor("#334155"))
        c.rect(width/2 - 25, viz_y - 25, 50, 50, fill=1, stroke=1)
    
    # Labels
    c.setFillColor(COLOR_TEXT_SUB)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(100, viz_y - 40, "Source / Internet")
    c.drawCentredString(width - 100, viz_y - 40, "Internal Network")
    c.setFillColor(COLOR_ACCENT_YELLOW)
    c.drawCentredString(width/2, viz_y - 40, "H-SAFE Firewall")
    
    current_y -= 140

    # 5. TRAFFIC ANALYSIS TIMELINE
    c.setFillColor(COLOR_TEXT_MAIN)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, current_y, "Traffic Analysis Timeline")
    current_y -= 20
    
    def draw_table_header(y):
        c.setFillColor(COLOR_PANEL)
        c.rect(40, y - 20, width - 80, 25, fill=1, stroke=0)
        c.setFillColor(COLOR_TEXT_MAIN)
        c.setFont("Helvetica-Bold", 9)
        c.drawString(50, y - 15, "TIME")
        c.drawString(120, y - 15, "SOURCE")
        c.drawString(240, y - 15, "DESTINATION")
        c.drawString(380, y - 15, "PROTO")
        c.drawString(430, y - 15, "PORT")
        c.drawString(480, y - 15, "ACTION")
        return y - 25

    current_y = draw_table_header(current_y)
    c.setFont("Helvetica", 9)
    
    # Render Timeline Rows
    # If timeline is empty, fall back to "No data"
    if not timeline:
        timeline = [{"timestamp": 0, "src_ip": "-", "dst_ip": "-", "protocol": "-", "dst_port": "-", "action": "INFO (No Timeline Data)"}]

    for i, packet in enumerate(timeline):
        if current_y < 50:
            new_page()
            current_y = height - 50
            current_y = draw_table_header(current_y)
            c.setFont("Helvetica", 9)

        # Striping
        if i % 2 == 1:
            c.setFillColor(colors.HexColor("#1e293b")) 
            c.rect(40, current_y - 15, width - 80, 20, fill=1, stroke=0)
        
        # Data
        c.setFillColor(COLOR_TEXT_SUB)
        ts_str = datetime.fromtimestamp(packet.get("timestamp", 0)).strftime("%H:%M:%S.%f")[:-3]
        c.drawString(50, current_y - 10, ts_str)
        
        c.setFillColor(COLOR_TEXT_MAIN)
        c.drawString(120, current_y - 10, str(packet.get("src_ip", "-")))
        c.drawString(240, current_y - 10, str(packet.get("dst_ip", "-")))
        c.drawString(380, current_y - 10, str(packet.get("protocol", "-")))
        c.drawString(430, current_y - 10, str(packet.get("dst_port", "-")))
        
        # Action Color
        action = packet.get("action", "ALLOW")
        if action == "DENY": c.setFillColor(COLOR_ACCENT_RED)
        elif action == "ALERT": c.setFillColor(COLOR_ACCENT_YELLOW)
        else: c.setFillColor(COLOR_ACCENT_GREEN)
        
        c.setFont("Helvetica-Bold", 9)
        c.drawString(480, current_y - 10, action)
        c.setFont("Helvetica", 9)
        
        current_y -= 18 # Row Height

    c.save()
